spring.application.name=H2database

server.port=8080
#spring.datasource.url=jdbc:mysql://localhost:3306/saran
#spring.datasource.username=root
#spring.datasource.password=yourpassword
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.datasource.url=jdbc:postgresql://localhost:5432/saran
spring.datasource.username=postgres
spring.datasource.password=yourpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
